<?php /** @var App $this */ ?>
<table>
    <tr>
        <td>place</td>
        <td>user</td>
        <td>score</td>
        <td>diff</td>
    </tr>
    <?php foreach ($this->getTop($this->getOffset()) as $top): ?>
        <tr>
            <td><?php echo $top['place'] ?></td>
            <td><?php echo $top['user'] ?></td>
            <td><?php echo $top['score'] ?></td>
            <?php if (isset($this->getDiff()[$top['user']])): ?>
                <td><?php echo($this->getDiff()[$top['user']] - $top['place']) ?></td>
            <?php else: ?>
                <td>0</td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>